"""v4 参数面：结构化 binding、三层身份、递归 schema、Cel 适配器与通用执行器。

模块边界
--------
* ``binding``  —— 结构化 binding + 字段白名单（注入防线，启动期自检）
* ``identity`` —— 身份/结构/值三层指纹与比对结论
* ``schema``   —— 递归节点模型（标量 / 颜色 / 向量 / 复合色带 / 分组）
* ``cel``      —— Cel 色阶适配器（能力驱动，探不到就降级，不猜 socket 名）
* ``draft``    —— 完整草稿校验（唯一入口，预设 / 预览 / 保存共用）
* ``executor`` —— 由固定模板生成写入与回读代码（原子、可回滚）
"""

from __future__ import annotations

from .binding import (
    BINDING_WHITELIST,
    READONLY_FIELDS,
    Binding,
    assert_allowed,
    assert_no_client_path,
    assert_whitelist_healthy,
    is_asset_binding,
    is_readonly,
)
from .draft import DraftError, baseline_values, validate_draft
from .executor import (
    JSON_MARKER,
    PlanOp,
    RAMP_MAX_ELEMENTS,
    RAMP_MIN_ELEMENTS,
    build_apply_code,
    build_readback_code,
    extract_json,
    normalise_ramp_elements,
    param_values,
    plan_values,
    sort_ops,
    verify_ops,
)
from .identity import (
    VERDICT_IDENTITY_MISSING,
    VERDICT_OK,
    VERDICT_STRUCTURE_CHANGED,
    VERDICT_VALUE_CHANGED,
    ObjectIdentity,
    ObjectRecord,
    Verdict,
    compare,
    records_from_describe,
    structure_hash,
    value_fingerprint,
    value_snapshot,
)
from .schema import (
    COSTS,
    KIND_BOOL,
    KIND_COLOR,
    KIND_ENUM,
    KIND_FLOAT,
    KIND_GROUP,
    KIND_INT,
    KIND_RAMP,
    KIND_VECTOR,
    REASON_KEYFRAMED_OR_CONSTRAINED,
    REASON_NOT_FOUND,
    REASON_REFERENCE_ONLY,
    REASON_ROLLBACK_UNAVAILABLE,
    REASON_STRUCTURAL,
    REASON_UNCONFIRMED_CAPABILITY,
    SCHEMA_VERSION,
    ColorNode,
    EnumNode,
    GroupNode,
    Node,
    RampElement,
    RampNode,
    ScalarNode,
    VectorNode,
    collect_bindings,
    flatten,
    max_cost,
    public_tree,
    walk,
)

__all__ = [
    "BINDING_WHITELIST",
    "COSTS",
    "ColorNode",
    "DraftError",
    "EnumNode",
    "GroupNode",
    "JSON_MARKER",
    "KIND_BOOL",
    "KIND_COLOR",
    "KIND_ENUM",
    "KIND_FLOAT",
    "KIND_GROUP",
    "KIND_INT",
    "KIND_RAMP",
    "KIND_VECTOR",
    "Node",
    "ObjectIdentity",
    "ObjectRecord",
    "PlanOp",
    "RAMP_MAX_ELEMENTS",
    "RAMP_MIN_ELEMENTS",
    "READONLY_FIELDS",
    "REASON_KEYFRAMED_OR_CONSTRAINED",
    "REASON_NOT_FOUND",
    "REASON_REFERENCE_ONLY",
    "REASON_ROLLBACK_UNAVAILABLE",
    "REASON_STRUCTURAL",
    "REASON_UNCONFIRMED_CAPABILITY",
    "RampElement",
    "RampNode",
    "SCHEMA_VERSION",
    "ScalarNode",
    "VERDICT_IDENTITY_MISSING",
    "VERDICT_OK",
    "VERDICT_STRUCTURE_CHANGED",
    "VERDICT_VALUE_CHANGED",
    "VectorNode",
    "Verdict",
    "assert_allowed",
    "assert_no_client_path",
    "assert_whitelist_healthy",
    "baseline_values",
    "build_apply_code",
    "build_readback_code",
    "collect_bindings",
    "compare",
    "extract_json",
    "flatten",
    "is_asset_binding",
    "is_readonly",
    "max_cost",
    "normalise_ramp_elements",
    "param_values",
    "plan_values",
    "public_tree",
    "records_from_describe",
    "sort_ops",
    "structure_hash",
    "validate_draft",
    "value_fingerprint",
    "value_snapshot",
    "verify_ops",
    "walk",
]
